config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index create destroy new show] do
      resources :comments, only: %i[create destroy]
      resources :likes, only: %i[create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true, length: { in: 1...100 }

  # after_save :update_comments_counter

  # private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  # after_save :update_likes_counter

  # private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { in: 1...250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    user_post = Post.find(params[:post_id])
    new_comment = Comment.new(author: current_user, post: user_post, text: comment_params)
    new_comment.update_comments_counter

    respond_to do |format|
      format.html do
        if new_comment.save
          flash[:success] = 'Comment succesful!'
          redirect_to user_post_path(current_user.id, user_post.id)
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    post = Post.find_by(id: comment.post_id)
    post.comments_counter -= 1
    comment.destroy
    post.save
    redirect_to user_posts_path(current_user.id, post.id)
    flash[:success] = 'Comment Deleted Successfully'
  end

  private

  def comment_params
    params.require(:data).permit(:comment)[:comment]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    user_post = Post.find(params[:post_id])
    user = User.find(params[:user_id])
    new_like = Like.new(author: user, post: user_post)
    new_like.update_likes_counter

    respond_to do |format|
      format.html do
        if new_like.save
          flash[:success] = 'Post Liked!'
          redirect_to user_post_path(current_user.id, user_post.id)
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
    @comments = @post.comments.includes([:author])
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.new(post_params)
    post.likes_counter = 0
    post.comments_counter = 0
    post.update_posts_counter
    respond_to do |format|
      format.html do
        if post.save
          flash[:success] = 'New post created successfully'
          redirect_to user_post_path(current_user.id, post.id)
        else
          render :new, alert: 'Error!'
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    user = User.find_by(id: post.author_id)
    user.posts_counter -= 1
    post.destroy
    user.save
    redirect_to user_posts_path(user.id)
    flash[:success] = 'Post Deleted Successfully'
  end

  private

  def post_params
    params.require(:data).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%=form_with url: user_post_comments_url(@user.id, @post.id), scope: :data do |f| %>
      <div>
        <%= f.label :comment %>
        <%= f.text_area :comment, :required=>true %>
        <%= f.submit "Comment"%>
      </div>
<% end %>

app/views/layouts/_header.html.erb
<%if user_signed_in? %>
  <nav>
   <h1 class='class-header'>My Blog App</h1>
   <div>
     <div class='nav-links d-flex a-center j-center'>
       <%= link_to "Home", root_path %>
       <%= link_to "Add new Post", new_user_post_path(:user_id => current_user.id) %>
     </div>
     <%= button_to "Log out", destroy_user_session_path, method: :delete %>
   </div>
  
  </nav>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render partial: 'layouts/header' %>
     <p class ="notice"><%= notice %></p>
     <p class ="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="user_c">
    <div class="user_data">
        <div class="user_img">
      <%= image_tag("avatar.png", width:'130px', height:'150px') %>
    </div>
      <h2><%= @user.name%></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <% @posts.each do |post| %>
  <div class="user_c">
    <div class="user_data_post">
     <%= link_to "#{post.title}", user_post_path(@user.id, post.id), class:"anything" %> 
     <h3><%= post.text%></h3>
      <p>Number of comments: <%= post.comments_counter %> <span>Number of likes: <%= post.likes_counter %></span></p>
    <%if can? :destroy, post %>
      <%= button_to "Delete Post", user_post_path(@user.id, post.id), method: :delete %>
    <%end%>
    </div>
  </div>
  <div class="comments">
    <% post.recent_comments.each do |comment| %>
        <h2><%="#{comment.author.name}: #{comment.text}" %></h2>
    <%end%>
  </div>
<%end%>
<div class="button-div">
  <button class="button"><%=link_to "New Post", new_user_post_path %></button>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%=form_with url: user_posts_path, scope: :data do |f| %>
  <div class= 'title'>
    <%=f.text_field :title, placeholder: 'Title', required: true %>
    <%=f.text_field :text, placeholder: 'Post..', required: true %>
  </div>

  <div class='submit-post'>
    <%=f.submit "Submit"%>
  </div>

<% end %>

app/views/posts/show.html.erb
<div class="user_c">
  <div class="user_data_post"> 
    <h2>#<%= @post.title %> by <span><%= @user.name %></span></h2>
    <h3 class = "post-comment">Comments <%= @post.comments_counter%>,  <span>Likes <%= @post.likes_counter%></span></h3>
    <p><%= @post.text %></p>  
  </div>
</div>
<div>
  <div class="comments">
  <% @comments.each do |comment| %>
    <h2><%= comment.author.name%>: <%= comment.text%></h2>
    <%if can? :destroy, comment %>
      <%= button_to "Delete", user_post_comment_path(@user.id, @post.id, comment.id), method: :delete %>
    <%end%>
  <%end%>
  </div>

  <%= render template: "comments/new"%>

     <%=form_with url: user_post_likes_url(@user.id, @post.id), scope: :data do |f| %>
      <div>
        <%= f.submit "Like"%>
      </div>
    <% end %>

</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="user_c">
    <div class="user_img">
      <%= image_tag("avatar.png", width:'130px', height:'150px') %>
    </div>
    <div class="user_data">
      <%= link_to user_path(user.id) do %>
      <h2><%= user.name%></h2>
      <% end %>
      <p>Number of posts: <%= user.posts_counter %></p>
    </div>
  </div>
<%end%>
  

app/views/users/show.html.erb
<div class="user_c">
  <div class="user_img">
    <%= image_tag("avatar.png", width:'130px', height:'150px') %>
  </div>
  <div class="user_data">
    <h2><%= @user.name%></h2>
    <p>Number of posts: <%= @user.posts_counter%></p>
  </div>
</div>

<div class="user_c2">
  <div class="user_data2">
    <h2>Bio</h2>
    <p class="bio"><%= @user.bio%></p>
  </div>
</div>

<% @user.recent_posts.each do |post| %>
  <div class="comment_c">
      <h2># Post : <%= post.title%></h2>
      <p><%= post.text%></p>
      <h3>Comment <%= post.comments_counter%>,  <span>Likes <%= post.likes_counter%></span></h3>
  </div>
<%end%>

<div class="button-div">
  <button class="button">
      <%= link_to "See all posts", user_posts_path(@user), {:class => "button_class"} %>
  </button>
</div> 